AllCops:
  NewCops: enable
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  CountAsOne: ['array', 'method_call', 'hash']
  Max: 30
  Severity: refactor
Metrics/CyclomaticComplexity:
  Max: 12
  Severity: refactor
Metrics/PerceivedComplexity:
  Max: 12
  Severity: refactor
Metrics/AbcSize:
  Max: 25
  Severity: refactor
