sonar.projectKey=Disenchanter
sonar.projectVersion=v3.1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=**/*_test.go

# Hardcoded translation string literal references are considered easier to maintain for now.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=go:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.go
