name: Create PR for new League Patch

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:

jobs:
  push_to_branch_and_create_pr:
    name: Create PR for new League Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit
        
      - id: patch
        name: Get patch info
        uses: marvinscham/get-league-patch@v1.1.1
        
      - name: Update patch in README shield
        run: sed -i "s/league%20patch-.*-brightgreen/league%20patch-${{ steps.patch.outputs.patch }}-brightgreen/g" README.md
        shell: bash
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          commit-message: Bump League Patch to ${{ steps.patch.outputs.patch }}
          title: Bump League Patch to ${{ steps.patch.outputs.patch }}
          body: |
            Review criteria:
            
            - [ ] Disenchanter can connect and issue actions
            
            This is an automated PR.
            <sub>[workflow](https://github.com/marvinscham/disenchanter/blob/master/.github/workflows/league-patch.yml).</sub>
          branch: update-league-patch
          labels: documentation, tests needed
